### PR TITLE
fixed the errors in the PaymentScreen.js

### PR DESCRIPTION
**Pull request by kishanRaj10**

### CODE REVIEW

**Review by dpak1999 — CHANGES_REQUESTED** [review]
it should be CheckOutSteps and not CheckoutSteps

**Comment by kishanRaj10** [comment]
> it should be CheckOutSteps and not CheckoutSteps

yeah right

**Comment by kishanRaj10** [comment]
> > it should be CheckOutSteps and not CheckoutSteps
> 
> yeah right



> > it should be CheckOutSteps and not CheckoutSteps
> 
> yeah right

done

**Review by dpak1999 — APPROVED** [review]
Great!!!

**Pull request merged**
